hydra:
  run:
    dir: logs/${network.name}_${run.distrib}_${now:%Y-%m-%d_%H-%M-%S}

network:
  name: realnvp
  layers: 32

train:
  steps: 100000
  samples: 1024

optimizer:
  name: adam
  lr: 1.0e-4
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.0
  decay_steps: 10000
  decay_ratio: 0.5

run:
  gpu: 0
  debug: False
  distrib: circles
  ckpt_path: null
  output: outputs
  display: 1

defaults:
  - network: realnvp
